package com.events.common;

/**
 * Created with IntelliJ IDEA.
 * User: kensen
 * Date: 1/30/14
 * Time: 11:08 AM
 * To change this template use File | Settings | File Templates.
 */
public enum Perm {
    ACCESS_CLIENTS_TAB,CREATE_NEW_CLIENT,DELETE_CLIENT,EDIT_CLIENT,
    ACCESS_EVENTS_TAB,CREATE_NEW_EVENT,DELETE_EVENT,
    EDIT_ROLE_PERMISSION,DELETE_ROLE,
    ACCESS_DASHBOARD_TAB, MANAGE_VENDOR_WEBSITE, MANAGE_TEAM_MEMBERS, MANAGE_ROLE_PERMISSION, MANAGE_PARTNER_VENDORS,
    EDIT_INVOICE,VIEW_INVOICE;
}
